function [Canopy,Error] = callComputeError(Error,Canopy,CanopyIteration)

Error.sunTleaf = nansum((CanopyIteration.sunTleaf(2:end) - ...
        Canopy.sunTleaf(2:end)).^2)/length(Canopy.z);
Error.shadeTleaf = nansum((CanopyIteration.shadeTleaf(2:end) - ...
    Canopy.shadeTleaf(2:end)).^2)/length(Canopy.z);
Error.windProfile = nansum((CanopyIteration.windProfile(2:end) - ...
    Canopy.windProfile(2:end)).^2)/length(Canopy.z); 
Error.caProfile = nansum((CanopyIteration.caProfile(2:end) - ...
    Canopy.caProfile(2:end)).^2)/length(Canopy.z);
Error.eaProfile = nansum((CanopyIteration.eaProfile(2:end)/1000 - ...
    Canopy.eaProfile(2:end)/1000).^2)/length(Canopy.z);
Error.tAirProfile = nansum((CanopyIteration.tAirProfile(2:end) - ...
    Canopy.tAirProfile(2:end)).^2)/length(Canopy.z); 

Error.loop = Error.loop + 1;

end
